//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCBilgisayar.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Computer_HardwareEntities : DbContext
    {
        public Computer_HardwareEntities()
            : base("name=Computer_HardwareEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Kategori_Tbl> Kategori_Tbl { get; set; }
        public virtual DbSet<Musteriler_Tbl> Musteriler_Tbl { get; set; }
        public virtual DbSet<Satıs_Tbl> Satıs_Tbl { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Urunler_Tbl> Urunler_Tbl { get; set; }
    }
}
