//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCBilgisayar.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Musteriler_Tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Musteriler_Tbl()
        {
            this.Satıs_Tbl = new HashSet<Satıs_Tbl>();
        }
    
        public int Musteri_Id { get; set; }
        public string Musteri_Ad { get; set; }
        public string Musteri_Soyad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Satıs_Tbl> Satıs_Tbl { get; set; }
    }
}
